import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.teams': 'Teams',
    'nav.characters': 'Characters',
    'nav.support': 'Support',
    'nav.leaderboard': 'Leaderboard',
    'nav.match': 'Match',
    'nav.admin': 'Admin',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.language': 'Language',
    'nav.mute': 'Mute',
    'nav.unmute': 'Unmute',
    'auth.titleLogin': 'Login to Support',
    'auth.titleRegister': 'Create Your Account',
    'auth.subtitle': 'Sign in to watch live matches, select your cartoon hero, and support your team.',
    'auth.fullName': 'Full Name',
    'auth.email': 'Email',
    'auth.phone': 'Pakistani Phone Number',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.register': 'Register',
    'auth.login': 'Login',
    'auth.createAccount': 'Create account',
    'auth.switchLogin': 'Login',
    'auth.switchRegister': 'Create account',
    'auth.phoneHint': 'Use format +92 3xx xxxxxxx',
    'auth.passwordMismatch': 'Passwords do not match.',
    'auth.invalidPhone': 'Please enter a valid Pakistani phone number like +92 300 1234567.',
    'home.heading': 'Home',
    'home.description': 'Live AI Match Arena',
    'home.liveMatch': 'Live AI Match',
    'home.liveMatchDesc': 'AI-controlled battle with live updates every few seconds.',
    'home.matchTimer': 'Match Timer',
    'home.live': 'Live',
    'home.finished': 'Finished',
    'home.teamA': 'Team A',
    'home.teamB': 'Team B',
    'home.aiScore': 'AI Score',
    'home.supportingTeam': 'Supporting Team',
    'home.supportButton': 'Support',
    'home.recentMatches': 'Recent Matches',
    'home.liveUpdates': 'Live Updates',
    'home.liveUpdatesText': 'Battle mechanics are simulated using AI decision flows, instantly updating score and status.',
    'home.highlight': 'Match Highlight',
    'home.highlightText': 'Your chosen team receives daily free support coins to cheer on your champion.',
    'support.heading': 'Support',
    'support.description': 'Give free coins to your favorite team',
    'support.availableCoins': 'Available Free Coins',
    'support.pulse': 'Support Pulse',
    'support.selectTeam': 'Select Team',
    'support.selectTeamDesc': 'Support your favorite team with free coins.',
    'support.givingTo': 'Giving coins to',
    'support.claim': 'Claim Daily Coins',
    'support.supportNow': 'Support Now',
    'support.totalCoins': 'Total Coins Given',
    'support.history': 'Support History',
    'support.pkrtitle': 'PKR Coin Packages',
    'support.pkrDesc': 'Top up your balance with local Pakistani payment options for fast support.',
    'support.priceLabel': 'PKR',
    'support.buy': 'Buy Now',
    'support.gatewayTitle': 'Upcoming Local Gateways',
    'support.gatewayText': 'JazzCash and EasyPaisa integration will be enabled for secure PKR deposits soon.',
  },
  ur: {
    'nav.home': 'ہوم',
    'nav.teams': 'ٹیمز',
    'nav.characters': 'کردار',
    'nav.support': 'حمایت',
    'nav.leaderboard': 'لیڈر بورڈ',
    'nav.match': 'میچ',
    'nav.admin': 'ایڈمن',
    'nav.profile': 'پروفائل',
    'nav.login': 'لاگ ان',
    'nav.logout': 'لاگ آؤٹ',
    'nav.language': 'زبان',
    'nav.mute': 'خاموش',
    'nav.unmute': 'آواز چلائیں',
    'auth.titleLogin': 'حمایت کے لیے لاگ ان کریں',
    'auth.titleRegister': 'اپنا اکاؤنٹ بنائیں',
    'auth.subtitle': 'براہ کرم لاگ ان ہو کر لائیو میچ دیکھیں، اپنے کارٹون ہیرو کا انتخاب کریں اور اپنی ٹیم کی حمایت کریں۔',
    'auth.fullName': 'مکمل نام',
    'auth.email': 'ای میل',
    'auth.phone': 'پاکستانی فون نمبر',
    'auth.password': 'پاس ورڈ',
    'auth.confirmPassword': 'پاس ورڈ کی تصدیق',
    'auth.register': 'رجسٹر',
    'auth.login': 'لاگ ان',
    'auth.createAccount': 'اکاؤنٹ بنائیں',
    'auth.switchLogin': 'لاگ ان',
    'auth.switchRegister': 'اکاؤنٹ بنائیں',
    'auth.phoneHint': 'فارمیٹ +92 3xx xxxxxxx استعمال کریں',
    'auth.passwordMismatch': 'پاس ورڈ ایک جیسے نہیں ہیں۔',
    'auth.invalidPhone': 'براہ کرم +92 300 1234567 جیسے درست پاکستانی فون نمبر درج کریں۔',
    'home.heading': 'ہوم',
    'home.description': 'لائیو AI میچ ایریا',
    'home.liveMatch': 'لائیو AI میچ',
    'home.liveMatchDesc': 'AI سے چلنے والی جنگ جس میں ہر چند سیکنڈ بعد اپ ڈیٹس آتے ہیں۔',
    'home.matchTimer': 'میچ ٹائمر',
    'home.live': 'لائیو',
    'home.finished': 'ختم',
    'home.teamA': 'ٹیم A',
    'home.teamB': 'ٹیم B',
    'home.aiScore': 'AI اسکور',
    'home.supportingTeam': 'حمایت کرنے والی ٹیم',
    'home.supportButton': 'حمایت',
    'home.recentMatches': 'حالیہ میچ',
    'home.liveUpdates': 'لائیو اپ ڈیٹس',
    'home.liveUpdatesText': 'جنگ کی میکانکس AI فیصلوں سے دکھائی جاتی ہیں اور اسکور اور حالت فوری طور پر اپ ڈیٹ ہوتی ہے۔',
    'home.highlight': 'میچ ہائی لائٹ',
    'home.highlightText': 'آپ کی منتخب کردہ ٹیم کو اپنے چیمپیئن کی حوصلہ افزائی کے لیے روزانہ مفت کوائن ملتے ہیں۔',
    'support.heading': 'حمایت',
    'support.description': 'اپنی پسندیدہ ٹیم کو مفت کوائن دیں',
    'support.availableCoins': 'دستیاب مفت کوائن',
    'support.pulse': 'سپورٹ نبض',
    'support.selectTeam': 'ٹیم منتخب کریں',
    'support.selectTeamDesc': 'اپنی پسندیدہ ٹیم کو مفت کوائنوں سے سپورٹ کریں۔',
    'support.givingTo': 'کوائن دے رہے ہیں',
    'support.claim': 'روزانہ کوائن حاصل کریں',
    'support.supportNow': 'ابھی سپورٹ کریں',
    'support.totalCoins': 'مجموعی دیے گئے کوائن',
    'support.history': 'سپورٹ ہسٹری',
    'support.pkrtitle': 'PKR کوائن پیکجز',
    'support.pkrDesc': 'مقامی پاکستانی ادائیگی کے اختیارات سے تیزی سے سپورٹ کے لیے اپنی بیلنس اپ ٹاپ کریں۔',
    'support.priceLabel': 'PKR',
    'support.buy': 'ابھی خریدیں',
    'support.gatewayTitle': 'آنے والے مقامی گیٹ ویز',
    'support.gatewayText': 'JazzCash اور EasyPaisa کا انٹیگریشن جلد ہی محفوظ PKR ڈپوزٹس کے لیے فعال کیا جائے گا۔',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('appLanguage') || 'en');

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
  }, [language]);

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  const value = useMemo(() => ({ language, setLanguage, t }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
